spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin
    virtual-host: /
#    listener:
#      simple:
#        #消费者手动确认
#        acknowledge-mode: manual

#业务参数
myQueue:
  name: queue-dev
  other: other-param-dev